# Generated by Django 3.2.7 on 2022-01-07 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RMCode', models.CharField(help_text='RM01', max_length=20, unique=True)),
                ('Material', models.CharField(max_length=20, unique=True)),
                ('Units', models.CharField(max_length=20)),
                ('Types', models.CharField(choices=[('Leather', 'Leather'), ('Paint', 'Paint'), ('Iron', 'Iron'), ('Plastic', 'Plastic')], default='Accounts', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RMDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNo', models.IntegerField(help_text='01', unique=True)),
                ('Date', models.DateField()),
                ('PlanNo', models.CharField(help_text='PLN01', max_length=20, unique=True)),
                ('CancelledDates', models.DateField()),
                ('PONo', models.CharField(help_text='PON01', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Material_Type', models.CharField(max_length=100)),
                ('ContactPersonName', models.CharField(max_length=100)),
                ('ContactPersonPhone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RMPurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=200)),
                ('TotalAmount', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=200)),
                ('CommitedDates', models.DateField()),
                ('Pending', models.CharField(max_length=200)),
                ('Received', models.CharField(max_length=200)),
                ('PONo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.rmdemand', to_field='PONo')),
                ('RMCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.rawmaterials', to_field='RMCode')),
                ('SID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.supplier', to_field='SID')),
            ],
        ),
        migrations.CreateModel(
            name='RMPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderedDate', models.DateField()),
                ('DNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DNOOrder', to='store.rmdemand', to_field='DNo')),
                ('PONo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='POOrder', to='store.rmdemand', to_field='PONo')),
            ],
        ),
        migrations.CreateModel(
            name='DemandedMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DemandedQuantity', models.CharField(max_length=200)),
                ('CurrentStock', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('Priority', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=50)),
                ('DNo', models.IntegerField()),
                ('RMCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.rawmaterials', to_field='RMCode')),
            ],
        ),
    ]
